# Generated by Django 5.1.3 on 2024-12-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя продукта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание продукта')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя продукта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание продукта')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
                ('category', models.CharField(max_length=150, verbose_name='Категория')),
                ('cost', models.FloatField(verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name', 'description', 'category', 'cost'],
            },
        ),
    ]
