# Generated by Django 5.1.3 on 2025-02-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publication_status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='статус публикации'),
        ),
    ]
